pipeline {
  agent any

  parameters {
    string(defaultValue: "", description: "Custom deployment name", name: "deployName")
    choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "Availability zone", name: "deployAZ")
    booleanParam(defaultValue: false, description: "Confirm deployment?", name: "deployConfirm")
  }

  stages {
    stage("Demo"){
      steps {
        echo "Deployment name is set to: ${params.deployName}"
        echo "Availability zone is set to: ${params.deployAZ}"
        echo "Confirmation is set to: ${params.deployConfirm}"
      }
    }
  }
}