pipeline {
  agent any

  stages{
    stage("Demo"){
      steps {
        myFunc("Hello from the demo stage!")
        sh """
          echo "Hello from the shell"
        """
      }
    }
  }
}

def myFunc(String myText) {
  echo "myText is set to: ${myText}"
}