pipeline {
  agent any

  parameters {
    booleanParam(defaultValue: false, description: "Enable service?", name: "myBoolean")
  }

  stages {
    stage("Demo"){
      steps {
        // anything with groovy needs to go inside the script block
        script {
          if(params.myBoolean == false){
            currentBuild.result = "SUCCESS"
            return // return stops the pipeline completely
          }
          else {
            echo "booleanParam is set to: TRUE"
          }
        }
      }
    }
  }
}